#端口配置
server:
  port: 9090
#数据库链接配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/haos?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
#日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #逻辑删除配置
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0


alipay:
  appId: 2021000121607408
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCfNv3W0RhzssVjl5Ll1orB7wWRDDM9wE2g/HqowVM4C6kFYbd9uUnZCPrqNYYDorTx4xVr/3JISeXmWh6EMVXRjgHQ/4avR2TDrw80pr+qJCAaNz9N8Rjluqh2lDC1LpaMnHVmOdAQomsQyh+7L/0aRe8zzbcvOY5Nzdt5Z6s5YO7wOm8OFZV5gDFWc+X0s2hddd/TuNeleaLsED03XrNUm7Q8HK8ui/Wi5WzOu8lyE0ia24QWUsCScjgwUqsPZmZfgtq1SUR7UyjVFEOBKbB8En1s2HH4nfs72QAgv5GKmdTtm1tQ4BP9HSBW2PIsaqbG2nSwUIaWKFjHubhOrEyJAgMBAAECggEAHpBq+GMZg5RtCipd29tstcAR3H9wEsmo3V+6mEzMkfTDFLJmjC8WuyBbMrzlpisE+25xfVMDeFcfWDIyq4PhCqJtPNbg3yMgd+RSUfQ01Q+sTfwPHgJLmkZT8reOBioUYpfifaZZh+f2D7oNj1yuBO4p9lLmeJ1e8Ra0rEC3gQMJzIYLM3DReoJZEdqzQa2NdfcimqBdBrKqe3V2kPXRdFR1cQYq7h42S0CDpOwtMfcHYFuJngb4ihxkRwP/GYOxukrZHDFa/vMIX1aJnI1puQIp5vHP26OU3XL01fUNVnsxG4VyVTE6Bj2MKp6nmEt/XWPbFjOwaUsxIyV0lvj91QKBgQDgBvAO8/93SwXPcSc6tbOLhKaz45oAzw+R1QaHZJVy5Si9NUh7JGVP6KcNiFgSX20nCBmM0x5G/cbIOXXbDSzz9qjREIEgALH2k9t1fB0KY8RMMETaQT/XNWw7HFILabAVm1TTCA9uee/Jk23FTivRHpP08KhQ2cZETiflvP1l6wKBgQC18BHVYPVmVFRCMG30zAQXn0XfAalGUuPjLpopRSe9c4pzjChs2IoPXZo5zh2C+o1cSkeC4UcaL93Kho45xJgUybzkFIY7JAHNgOnVqzY8HPziChk+Ruo6OWvESVlp+epOHDMASOfHKKL2mDkigxBDvjn+3MJtGoBZaFKbMWy2WwKBgBc8APe8DJnFuSOLm8L2B1oH9vYfO+CrmPTKADRYlTtmUvRUq2DCJJPGEFVR97hoFzz+FRBK8Q/x0AUCGJwQYMIoqdeM+6djCxIEwbUMm0JxmHFCbFGqhMGAM+pphITUgEOtaX29j0Qo91qTpMXa1qaIolW8A+jmvS5mYLLuB+XjAoGBAKf1xyDr7+DWPSsVtozlw2ljWoez6ufHIibbIOq0sylM/yYI4FEL3visevKee9QtJk9rK3WCL7fXNLQBYE+oVJXsX/tXj0wNw7RKLJVbCCiawkKS/BboNNgnpnuBE5CobUxK8DJ1G7RaqYdppGVeBafkd3n3p249pvvjOU+YYzo9AoGBAMdOkB76ymzyqvV8ZVYj6EEOAh29rw5XP0mTm7/SV3rOmHkKYeERjb85SwXupqxcidIDZSvrlXpF6et/P82uotCDDgGDqNzXA2pPdFyHrmmuGs/q8TRT3ADDbB0Uc5Mv8xZGBNnNWurvG4BaotQhTel3Rg79zqCtT83pIdAc4p45
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhmOCUcj9r0G8ldThGJuRFxNa3VTszFPwNq/lBxEXBeuxKviyRRsyF+MGb+9lIKOihIn+p8c/D49JDbA+RmOBEIZplKvPpzYbrpaPj3AEvgaRkCJL/5dwyUrajcIy+QnmVoc0YKhFeHOrLhcimwQHAWceeAbWQySmJyxiAMe9oCXdA0Jl92waIF3nj+5BTpPjj7a/gJVLxPeE2+KWPnmbpHXeNa+vCOfnSHS/tpOGU6LHELhUQqTWZIdU1ff38z96ANJ9Q8HA8ZQ+3lMnFl2+F3OFLlDrXqfyyqdT6K1dFwNXaZHJ1Kj5LV9SbDMvFDLcU00Nco0t92Stzu42C39G+QIDAQAB
  notifyUrl: http://pkgck5.natappfree.cc/back/user/t1
